name: Waka Readme

on:
  schedule:
    # Jalan otomatis setiap jam 12 malam
    - cron: '0 0 * * *'
  workflow_dispatch: # Supaya bisa dijalankan manual juga

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_MASKED_TIME: True
          SHOW_TIME: true
          SHOW_TOTAL: true
          TIME_RANGE: "all_time"