name: Waka Readme

on:
  schedule:
    # Jalan otomatis setiap jam 12 malam
    - cron: '0 0 * * *'
  workflow_dispatch: # Supaya bisa dijalankan manual juga

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_LOC_CHART: "False"
          SHOW_PROJECTS: "False"
          SHOW_PROFILE_VIEWS: "False"
          # Ini untuk menampilkan bahasa & waktu seperti gambar Anda
          SHOW_LINES_OF_CODE: "False" 
          SHOW_SHORT_INFO: "False"
          SHOW_DAYS_OF_WEEK: "False"
          SHOW_LANGUAGE: "True" 
          SHOW_OS: "False"
          SHOW_COMMIT: "False"
          SHOW_EDITORS: "False"
          SHOW_TIMEZONE: "False"